# Generated by Django 5.1.6 on 2025-02-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=150)),
                ('b_age', models.IntegerField()),
                ('b_title', models.CharField(max_length=200)),
                ('b_contant', models.ImageField(upload_to='',)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
